artifact: band_aid
artifacts_file: data/artifacts_isic.json
batch_size: 12
cav_mode: cavs_max
cav_scope:
- NV
checkpoint_dir_corrected: PATH_TO_CHECKPOINTS_CORRECTED
ckpt_path: PATH_TO_CHECKPOINT
criterion: all_logits_random
data_paths:
- PATH_TO_ISIC2019
dataset_name: isic
device: cuda
dir_precomputed_data: PATH_TO_PRECOMPUTED_DATA
direction_mode: signal
img_size: 224
lamb: 100000.0
layer_name: features.28
loss: cross_entropy
lr: 0.0005
method: RRClarc
model_name: vgg16
num_epochs: 10
optimizer: sgd
plot_alignment: false
wandb_api_key: YOUR_WANDB_KEY
wandb_project_name: WANDB_PROJECT_NAME
